const timestamps = {
  created_at: new Date(),
  updated_at: new Date(),
};

module.exports = {
  up: queryInterface => queryInterface.bulkInsert(
    'ba',
    [{
        id: 1,
        ba_name: '前端',
        description: '前端吧,带你走进Web前端开发世界',
        theme_url: './images/ba_images/img_1.jpg',
        fans_count: 3,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 2,
        ba_name: '软件工程',
        description: '与你一起分享软件工程的知识海洋',
        theme_url: './images/ba_images/img_2.jpg',
        fans_count: 2,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 3,
        ba_name: '江西财经大学',
        description: '信而达礼 敏而好学 廉而知耻 毅而弥坚',
        theme_url: './images/ba_images/img_3.jpg',
        fans_count: 2,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 4,
        ba_name: '少年三国志',
        description: '吧主很懒噢,本吧还没有任何介绍',
        theme_url: './images/ba_images/img_4.jpg',
        fans_count: 2,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 5,
        ba_name: 'php',
        description: 'PHP交流社区',
        theme_url: './images/ba_images/img_5.jpg',
        fans_count: 1,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 6,
        ba_name: '美工',
        description: '有图有真相',
        theme_url: './images/ba_images/img_6.jpg',
        fans_count: 2,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 7,
        ba_name: 'python',
        description: 'python学习交流基地',
        theme_url: './images/ba_images/img_7.jpg',
        fans_count: 2,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 8,
        ba_name: 'java',
        description: '有问题为什么不先问问隔壁C++吧呢？',
        theme_url: './images/ba_images/img_8.jpg',
        fans_count: 2,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 9,
        ba_name: 'C++',
        description: '有问题为什么不先问问隔壁C语言吧呢？',
        theme_url: './images/ba_images/img_9.jpg',
        fans_count: 1,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 10,
        ba_name: 'android',
        description: '安卓数码产品讨论区,数码综合类讨论区',
        theme_url: './images/ba_images/img_10.jpg',
        fans_count: 2,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 11,
        ba_name: '电影票房',
        description: '票房风波起，银幕百态生！',
        theme_url: './images/ba_images/img_11.jpg',
        fans_count: 1,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 12,
        ba_name: '黎明杀机',
        description: '黎明杀机 中国玩家交流社区',
        theme_url: './images/ba_images/img_12.jpg',
        fans_count: 2,
        tie_count: 1,
        ...timestamps,
      },
      {
        id: 13,
        ba_name: '娱乐圈',
        description: '贴吧娱乐界的风向标',
        theme_url: './images/ba_images/img_13.jpg',
        fans_count: 1,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 14,
        ba_name: '爱情',
        description: '遇见你，我不曾后悔',
        theme_url: './images/ba_images/img_14.jpg',
        fans_count: 0,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 15,
        ba_name: '中国好声音',
        description: '中国好声音',
        theme_url: './images/ba_images/img_15.jpg',
        fans_count: 0,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 16,
        ba_name: '快乐大本营',
        description: '快乐大本营，天天好心情',
        theme_url: './images/ba_images/img_16.jpg',
        fans_count: 0,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 17,
        ba_name: '世界杯',
        description: '球迷盛宴，精彩不断',
        theme_url: './images/ba_images/img_17.jpg',
        fans_count: 1,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 18,
        ba_name: '毕业照',
        description: '那些毕业照，是青春最美好的回忆',
        theme_url: './images/ba_images/img_18.jpg',
        fans_count: 1,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 19,
        ba_name: '校园怪谈',
        description: '新奇、灵异、卧谈话题，我们都是被吓大的。',
        theme_url: './images/ba_images/img_19.jpg',
        fans_count: 0,
        tie_count: 0,
        ...timestamps,
      },
      {
        id: 20,
        ba_name: '中国历史',
        description: '一点一滴的历史，一尺一步的旅程',
        theme_url: './images/ba_images/img_20.jpg',
        fans_count: 0,
        tie_count: 0,
        ...timestamps,
      }
    ], {},
  ),

  down: (queryInterface, Sequelize) => {
    const {
      Op
    } = Sequelize;
    return queryInterface.bulkDelete('ba', {
      id: {
        [Op.between]: [1, 20]
      }
    }, {});
  },
}